//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace consorciosimulacao {
    
    
    public partial class Cadastro {
        
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        
        protected System.Web.UI.WebControls.Label lblNome;
        
        protected System.Web.UI.WebControls.TextBox txtNome;
        
        protected System.Web.UI.WebControls.Label lblLogin;
        
        protected System.Web.UI.WebControls.TextBox txtLogin;
        
        protected System.Web.UI.WebControls.Label Label2;
        
        protected System.Web.UI.WebControls.TextBox txtSenha;
        
        protected System.Web.UI.WebControls.Label lblConfSenha;
        
        protected System.Web.UI.WebControls.TextBox txtConfSenha;
        
        protected System.Web.UI.WebControls.Label lblMensagem;
        
        protected System.Web.UI.WebControls.Button btnCadastrar;
        
        protected System.Web.UI.WebControls.Button btnVoltar;
    }
}
