//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace consorciosimulacao {
	
	
	public partial class Simulacao {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Label lblUsuario;
		
		protected System.Web.UI.WebControls.Label lblTipo;
		
		protected System.Web.UI.WebControls.Label lblCondicao;
		
		protected System.Web.UI.HtmlControls.HtmlSelect condicao;
		
		protected System.Web.UI.WebControls.Label lblLocalizacao;
		
		protected System.Web.UI.WebControls.DropDownList ddlEstado;
		
		protected System.Web.UI.WebControls.DropDownList ddlCidade;
		
		protected System.Web.UI.WebControls.Label lblPor;
		
		protected System.Web.UI.WebControls.RadioButtonList tipoOpcao;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl optValor;
		
		protected System.Web.UI.WebControls.Label lblValor;
		
		protected System.Web.UI.WebControls.TextBox txtValor;
		
		protected System.Web.UI.WebControls.Label lblPercentual;
		
		protected System.Web.UI.WebControls.TextBox txtPercentual;
		
		protected System.Web.UI.WebControls.Label lblNumeroPercentual;
		
		protected System.Web.UI.WebControls.TextBox txtPercentualDe;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl optRenda;
		
		protected System.Web.UI.WebControls.Label lblRenda;
		
		protected System.Web.UI.WebControls.TextBox txtRenda;
		
		protected System.Web.UI.WebControls.Label lblIdade;
		
		protected System.Web.UI.WebControls.TextBox txtIdade;
		
		protected System.Web.UI.WebControls.Button button1;
	}
}
